# Generated by Django 3.2.5 on 2021-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(verbose_name='기수')),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, verbose_name='연락처')),
                ('profile', models.ImageField(null=True, upload_to='', verbose_name='프로필 사진')),
                ('introduction', models.TextField(max_length=1000, null=True, verbose_name='자기소개')),
            ],
        ),
    ]
