# Generated by Django 3.2.5 on 2021-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='프로필 사진'),
        ),
    ]
