# Generated by Django 3.2.5 on 2021-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_member_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='프로필 사진'),
        ),
    ]
